server:
  AppMode: debug
  HttpPort: :8080
  JwtKey: <YourJwtKey>
  JwtIssuer: travelfriend
datasource:
  dirverName: mysql
  host: localhost
  port: 3306
  database: bubble
  username: root
  password: 1998slr!
  charset: utf8
